Greek islands
========================================================

```{r}
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/profiles2.R"))
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/image.R"))
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/features.R"))
```

### Profiles

```{r}
makeProfile2.allSamp("greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean")
```

```{r greek_islands_v2_W25F200_dnase_h3k4me1_h3k27ac_tk79, fig.width=4, fig.height=12, dev=c("png", "pdf")}
par(mfrow=c(4,1), mar=c(2,2,2,2))
plot2("greek_islands_v2_W25F200_both_chr", "d3a_het_dnase_sort_q30", data_type="rpkm/mean", fname="manual", y.vals=c(0, 2.2))
plot2("greek_islands_v2_W25F200_both_chr", "moe_h3k4me1_rmdup", data_type="rpkm/mean", y.vals=c(0,3))
plot2("greek_islands_v2_W25F200_both_chr", "moe_h3k27ac_rmdup", data_type="rpkm/mean", y.vals=c(0,3))
plot2("greek_islands_v2_W25F200_both_chr", "moe_tk79", data_type="rpkm/mean", fname="manual", y.vals=c(0, 16))
```

### Images
```
positionMatrix.all("greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean")
```

```{r}
mk4 <- makeImage("moe_h3k4me1_rmdup", "greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean", image=FALSE)
ind <- which(is.na(mk4), arr.ind=T)
mk4[ind] <- 0
mk4.pc <- prcomp(mk4)
mk4.pred <- predict(mk4.pc, mk4)
```

```{r}
MP.heat(mk4[order(mk4.pred[,1]),], range=c(0,4))
```

```{r}
ac27 <- makeImage("moe_h3k27ac_rmdup", "greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean", image=FALSE)
ind <- which(is.na(ac27), arr.ind=T)
ac27[ind] <- 0
ac27.pc <- prcomp(ac27)
ac27.pred <- predict(ac27.pc, ac27)
```

```{r}
MP.heat(ac27[order(ac27.pred[,1]),], range=c(0,4))
```

```{r}
dnase <- makeImage("d3a_het_dnase_sort_q30", "greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean", image=FALSE)
ind <- which(is.na(dnase), arr.ind=T)
dnase[ind] <- 0
dnase.pc <- prcomp(dnase)
dnase.pred <- predict(dnase.pc, dnase)
```

```{r}
MP.heat(dnase[order(dnase.pred[,1]),], range=c(0,4))
```

```{r}
tk79 <- makeImage("moe_tk79", "greek_islands_v2_W25F200_both_chr", data_type="rpkm/mean", image=F)
ind <- which(is.na(tk79), arr.ind=T)
tk79[ind] <- 0
tk79.pc <- prcomp(tk79)
tk79.pred <- predict(tk79.pc, tk79)

```

```{r}
MP.heat(tk79[order(tk79.pred[,1]),], range=c(0,40))
```


#### Ordered by DNase PC1
```{r greek_islands_v2_en_marks_ordered_by_dnase_pc1, dev=c("png", "pdf")  }
MP.heat(dnase[order(dnase.pred[,1]),], range=c(0,4))
MP.heat(mk4[order(dnase.pred[,1]),], range=c(0,4))
MP.heat(ac27[order(dnase.pred[,1]),], range=c(0,4))
MP.heat(tk79[order(dnase.pred[,1]),], range=c(0,40))
```

#### Cluster

```{r}
feat <- makeFeatureMatrix2("greek_islands_v2_chr", "en_marks", data_type="rpkm/mean")
mat_score <- read.delim("~/data/greek/greek_islands_v3", header=F)
feat$mat_score <- mat_score[match(rownames(feat), mat_score[,4]),5]
feat.s <- as.data.frame(scale(feat))
colnames(feat.s) <- c("DHS", "H3K27ac", "H3K4me1", "H3K79me3", "Score")
```

```{r}
feat.s.dist <- dist(feat.s[,c(1:3, 5)])
feat.s.hc <- hclust(feat.s.dist, method="ward")
```

```{r greek_islands_v2_en_marks_hclust, fig.height=6, fig.width=5, dev=c("png", "pdf")}
lab.palette <- colorRampPalette(c("black","yellow"), space="Lab")
heatmap.2(as.matrix(feat.s), Rowv=as.dendrogram(feat.s.hc), Colv=F, dendrogram="row", trace="none", col=lab.palette, margins=c(9,5))
```

```{r}
feat.s.pc <- prcomp(feat.s[,1:4])
feat.s.pred <- predict(feat.s.pc, feat.s)
par(mfrow=c(1,2))
plot(feat.s.pc)
biplot(feat.s.pc)
```

```{r}
heatmap.2(as.matrix(feat.s[order(feat.s[,1]), 1:5]), Rowv=F, Colv=F, trace="none", col=lab.palette)
```

```{r}
feat.s.pc <- prcomp(feat.s[,1:5])
feat.s.pred <- predict(feat.s.pc, feat.s)
par(mfrow=c(1,2))
plot(feat.s.pc)
biplot(feat.s.pc)
```

```{r}
heatmap.2(as.matrix(feat.s[order(feat.s.pred[,1]), 1:5]), Rowv=F, Colv=F, trace="none", col=lab.palette)
```

```{r}
library(mclust)
mc <- Mclust(feat.s[,1:3], G=2)
```

```{r}
feat.s.k2 <- kmeans(feat.s, centers=2)
feat.s.k3 <- kmeans(feat.s, centers=3)
```

```{r}
feat.s$mc2 <- mc$classification
feat.s$k2 <- feat.s.k2$cluster
feat.s$k3 <- feat.s.k3$cluster
```

```{r, fig.width=12, fig.height=4}
library(gridExtra)
gg1 <- ggplot(feat.s, aes(moe_h3k27ac_rmdup, moe_h3k4me1_rmdup, color=factor(mc2))) + geom_point() + theme(legend.position="none") 
gg2 <- ggplot(feat.s, aes(moe_h3k27ac_rmdup, d3a_het_dnase_sort_q30, color=factor(mc2))) + geom_point() + theme(legend.position="none")
gg3 <- ggplot(feat.s, aes(moe_h3k4me1_rmdup, d3a_het_dnase_sort_q30, color=factor(mc2))) + geom_point() + theme(legend.position="none")
gg4 <- ggplot(feat.s, aes(mat_score, d3a_het_dnase_sort_q30, color=factor(mc2))) + geom_point() + theme(legend.position="none")
grid.arrange(gg1, gg2, gg3, gg4, nrow=2, ncol=2)

```


```{r}
feat.sm <- melt(feat.s)
feat.sm$id <- rownames(feat.s)
feat.sm$k3 <- feat.s.k3$cluster
```

```{r}
gg <- ggplot(feat.sm, aes())
```



```{r}
pc <- cbind(dnase.pred[,1], tk79.pred[,1], mk4.pred[,1], ac27.pred[,1])
colnames(pc) <- c("DNase", "tk79", "mk4", "ac27")
pc <- scale(pc)
pc.dist <- dist(pc)
pc.hclust <- hclust(pc.dist, method="ward")
```

```{r, fig.height=10, fig.width=5}
lab.palette <- colorRampPalette(c("yellow", "black","blue"), space="Lab")
heatmap.2(pc, Rowv=as.dendrogram(pc.hclust), Colv=FALSE, dendrogram="row", trace="none", cexCol=1, cexRow=1, col=lab.palette)
```


