Developmental cells -- replicates, TSS
========================================================

### Define developmentally regulated sets
```{r}
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/profiles2.R"))
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/image.R"))
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/modeling.R"))
library(mclust)
```

```
rna <- readRDS("~/s2/analysis/rna/rdata/omp_ngn_icam_mrna_ucsc_fpkm_1log2.rds")
rna <- rna[-grep("Olfr", rna$id),]
```

```
mc <- apply(rna[,1:3], 2, function(x) Mclust(x, G=2, modelName="E"))
```

```
mc.u2 <- lapply(mc, function(x) {
  a <- as.logical(x$classification-1)
  names(a) <- names(x$classification)
  return(a)})
```

```
bool.matrix <- matrix(NA, nrow=nrow(rna), ncol=3, dimnames=list(rna$id, c("omp", "ngn", "icam")))
for (i in 1:3) {
  bool.matrix[,i] <- mc.u2[[i]][match(rownames(bool.matrix), names(mc.u2[[i]]))] 
}
bool.matrix <- na.omit(bool.matrix)
```

```
omp.sp <- bool.matrix[apply(bool.matrix, 1, function(x) x[1] & !(x[2] | x[3])),]
ngn.sp <- bool.matrix[apply(bool.matrix, 1, function(x) x[2] & !(x[1] | x[3])),]
icam.sp <- bool.matrix[apply(bool.matrix, 1, function(x) x[3] & !(x[2] | x[1])),]
omp.ngn <- bool.matrix[apply(bool.matrix, 1, function(x) (x[1] & (x[2]) & ! x[3])),]
ngn.icam <- bool.matrix[apply(bool.matrix, 1, function(x) (x[2] & (x[3]) & ! x[1])),]
```

```
rna$class <- NA
rna$class[rna$id %in% rownames(omp.sp)] <- "mosn-specific"
rna$class[rna$id %in% rownames(ngn.sp)] <- "gbc-specific"
rna$class[rna$id %in% rownames(icam.sp)] <- "hbc-specific"
rna$class[rna$id %in% rownames(omp.ngn)] <- "mosn/gbc-common"
rna$class[rna$id %in% rownames(ngn.icam)] <- "gbc/hbc-common"
```

```
tss <- read.delim("~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200", header=F)
```

```
write.table(tss[tss[,4] %in% rownames(omp.sp),], file="~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam", quote=F, sep="\t", row.names=F, col.names=F)
write.table(tss[tss[,4] %in% rownames(ngn.sp),], file="~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam", quote=F, sep="\t", row.names=F, col.names=F)
write.table(tss[tss[,4] %in% rownames(icam.sp),], file="~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn", quote=F, sep="\t", row.names=F, col.names=F)
write.table(tss[tss[,4] %in% rownames(omp.ngn),], file="~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam", quote=F, sep="\t", row.names=F, col.names=F)
write.table(tss[tss[,4] %in% rownames(ngn.icam),], file="~/lib/annotations_hires/refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp", quote=F, sep="\t", row.names=F, col.names=F)
```

```{r}
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam_chr", data_type="rpkm/mean", rm.outliers=0.01)
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam_chr", data_type="rpkm/mean", rm.outliers=0.01)
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam_chr", data_type="rpkm/mean", rm.outliers=0.01)
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp_chr", data_type="rpkm/mean", rm.outliers=0.01)
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn_chr", data_type="rpkm/mean", rm.outliers=0.01)
```

```{r}
positionMatrix.all("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam_chr", data_type="rpkm/mean")
positionMatrix.all("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam_chr", data_type="rpkm/mean")
positionMatrix.all("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam_chr", data_type="rpkm/mean")
positionMatrix.all("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp_chr", data_type="rpkm/mean")
positionMatrix.all("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn_chr", data_type="rpkm/mean")
```

```{r}
samples <- c("omp_hmc_rep1_q30_rmdup_extend300_mean_omp_hmc_rep2_q30_rmdup", 
             "ngn_hmc_rep1_q30_rmdup_extend300_mean_ngn_hmc_rep2_q30_rmdup", 
             "icam_hmc_rep1_q30_rmdup_extend300_mean_icam_hmc_rep2_q30_rmdup")
o.ni <- lapply(samples, function(x) makeImage(x, "refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam_chr", data_type="rpkm/mean", image=F))
on.i <- lapply(samples, function(x) makeImage(x, "refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam_chr", data_type="rpkm/mean", image=F))
n.oi <- lapply(samples, function(x) makeImage(x, "refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam_chr", data_type="rpkm/mean", image=F))
ni.o <- lapply(samples, function(x) makeImage(x, "refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp_chr", data_type="rpkm/mean", image=F))
i.on <- lapply(samples, function(x) makeImage(x, "refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn_chr", data_type="rpkm/mean", image=F))

comb <- list(o.ni, on.i, n.oi, ni.o, i.on)
for (i in 1:length(comb)) names(comb[[i]]) <- c("omp", "ngn", "icam")
```


Significance testing
```{r}
perm <- lapply(comb, permutationTest.matList)
```


```{r refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam_omp_ngn_icam_rep, fig.height=4, fig.width=4, dev=c("png", "pdf")}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_vs_ngn_icam_chr", "cells_hmc_rep", data_type="rpkm/mean", group2="trim0.01", cols=col3, lab="TSS", y.vals=c(0,1.4))
plotSigLine(perm[[1]][,2], step=5, yval=1.3, col=col3[1])
```

```{r refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam_omp_ngn_icam_rep, fig.height=4, fig.width=4, dev=c("png", "pdf")}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_omp_ngn_vs_icam_chr", "cells_hmc_rep", data_type="rpkm/mean", group2="trim0.01", cols=col3, lab="TSS", y.vals=c(0, 1.4))                                                                                                                                           
plotSigLine(perm[[2]][,2], step=5, yval=1.3, col=col3[1])
plotSigLine(perm[[2]][,3], step=5, yval=1.25, col=col3[2])
```

```{r refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam_omp_ngn_icam_rep, fig.height=4, fig.width=4, dev=c("png", "pdf")}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_vs_omp_icam_chr", "cells_hmc_rep", data_type="rpkm/mean", group2="trim0.01", cols=col3, lab="TSS", y.vals=c(0, 1.4))
plotSigLine(perm[[3]][,2], step=5, yval=1.3, col=col3[1])
plotSigLine(perm[[3]][,3], step=5, yval=1.25, col=col3[2])
```


```{r refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp_omp_ngn_icam_rep, fig.height=4, fig.width=4, dev=c("png", "pdf")}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_ngn_icam_vs_omp_chr", "cells_hmc_rep", data_type="rpkm/mean", group2="trim0.01", cols=col3, lab="TSS", y.vals=c(0, 1.4))
```


```{r refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn_omp_ngn_icam_rep, fig.height=4, fig.width=4, dev=c("png", "pdf")}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_omp_ngn_icam_mrna_ucsc_fpkm_1log2_mclust_icam_vs_omp_ngn_chr", "cells_hmc_rep", data_type="rpkm/mean", group2="trim0.01", cols=col3, lab="TSS", y.vals=c(0, 1.4))
plotSigLine(perm[[5]][,2], step=5, yval=1.3, col=col3[3])
```