rDNA analysis 
========================================================

```{r}
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/profiles2.R"))
library(ggplot2)
```

```{r, warning=FALSE, message=FALSE, error=FALSE, results='hide'}
makeProfile2.allSamp("rmsk_rRNA_start_W25F200_both_chr", data_type="bam_extend/mean_chrom_mean_0", rm.outliers=0.01)
makeProfile2.allSamp("rmsk_rRNA_start_W25F200_both_chr", data_type="bam_ends/mean", rm.outliers=0.01)
makeProfile2.allSamp("rmsk_rRNA_start_W25F200_both_chr", data_type="rpkm/mean", rm.outliers=0.01)

```

```{r, fig.width=8, fig.height=4}
par(mfrow=c(1,2), mar=c(2,2,2,2))
plot2.several("rmsk_rRNA_start_W25F200_both_chr", "d3a_hmc", data_type="rpkm/mean", group2="trim0.01", cols=col2, y.vals=c(.2, 1))
plot2.several("rmsk_rRNA_start_W25F200_both_chr", "d3a_mc", data_type="rpkm/mean", group2="trim0.01", cols=col2, y.vals=c(0, .6))
```

```{r, fig.width=8, fig.height=4}
par(mfrow=c(1,1))
plot2.several("rmsk_rRNA_start_W25F200_both_chr","d3a_nuc_extend", data_type="bam_extend/mean_chrom_mean_0", group2="trim0.01", cols=col2, y.vals=c(.8, 1.4), range=c(101, 300))
```