D3xOG 5hmC/5mC TSS
========================================================

```{r}
opts_chunk$set(warning=FALSE, message=FALSE, error=FALSE)
library(plyr)
library(reshape2)
library(ggplot2)
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/profiles2.R"))
suppressPackageStartupMessages(source("~/src/seqAnalysis/R/image.R"))
```

```{r}
makeProfile2.allSamp("refGene_noRandom_order_outsides2_tss_W25F200_chr", data_type="rpkm/mean", rm.outliers=0.01)
```

```{r}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_chr", "d3xog_hmc", data_type="rpkm/mean", cols=col3, group2="trim0.01")
```

```{r}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_chr", "d3xog_mc", data_type="rpkm/mean", cols=col3, group2="trim0.01")
```

```{r}
plot2.several("refGene_noRandom_order_outsides2_tss_W25F200_chr", "tt3_rep", data_type="rpkm/mean", cols=col2, group2="trim0.01")
```

```{r}
makeProfile2.allSamp("gene_whole_W200N50F50_chr", data_type="rpkm/mean", rm.outliers=0.01)
```

```{r gene_whole_W200N50F50_d3a_hmc, fig.width=6, fig.height=4.5, dev=c("png", "pdf")}
plot2.several("gene_whole_W200N50F50_chr", "d3a_hmc", data_type="rpkm/mean", cols=col3[c(1,3)], group2="trim0.01", y.vals=c(0, .8))
```

```{r gene_whole_W200N50F50_d3a_mc, fig.width=6, fig.height=4.5, dev=c("png", "pdf")}
plot2.several("gene_whole_W200N50F50_chr", "d3a_mc", data_type="rpkm/mean", cols=col3[c(1,3)], group2="trim0.01", y.vals=c(0, .8))
```

```{r gene_whole_W200N50F50_d3xog_hmc, fig.width=6, fig.height=4.5, dev=c("png", "pdf")}
plot2.several("gene_whole_W200N50F50_chr", "d3xog_hmc", data_type="rpkm/mean", cols=col3, group2="trim0.01",  y.vals=c(0, .8))
```

```{r gene_whole_W200N50F50_d3xog_mc, fig.width=6, fig.height=4.5, dev=c("png", "pdf")}
plot2.several("gene_whole_W200N50F50_chr", "d3xog_mc", data_type="rpkm/mean", cols=col3, group2="trim0.01")
```



```{r}
positionMatrix.all("gene_whole_W200N50F50_chr", data_type="rpkm/mean")
```

```{r}
wt.hmc <- makeImage("omp_hmc_rep1_mean_omp_hmc_rep2", "gene_whole_W200N50F50_chr", data_type="rpkm/mean", image=F)
het.hmc <- makeImage("d3xog_het_hmc_paired_q30", "gene_whole_W200N50F50_chr", data_type="rpkm/mean", image=F)
ko.hmc <- makeImage("d3xog_ko_hmc_paired_q30", "gene_whole_W200N50F50_chr", data_type="rpkm/mean", image=F)
```

```{r}
wt.hmc.pc <- prcomp(wt.hmc[, 51:100])
wt.hmc.pred <- predict(wt.hmc.pc, wt.hmc)
```

```{r}
MP.heat(wt.hmc[order(wt.hmc.pred[,1]),], range=c(0,2), average=50)
```

```{r}
MP.heat(het.hmc[order(wt.hmc.pred[,1]),], range=c(0,2), average=50)
```

```{r}
MP.heat(ko.hmc[order(wt.hmc.pred[,1]),], range=c(0,2), average=50)
```


